name: Deploy para GitHub Pages

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clona o repositório
        uses: actions/checkout@v4

      - name: Verifica estrutura do repositório
        run: ls -R ${{ github.workspace }}

      - name: Cria pasta de build
        run: |
          mkdir ${{ github.workspace }}/deploy
          cp -r ${{ github.workspace }}/docs/HomePage/* ${{ github.workspace }}/deploy/
          cp -r ${{ github.workspace }}/docs/Global ${{ github.workspace }}/deploy/

      - name: Configura GitHub Pages
        uses: actions/configure-pages@v3

      - name: Faz deploy para Pages
        uses: actions/deploy-pages@v4
        with:
          folder: deploy